// @flow
import {StyleSheet} from 'react-native';
import {Colors, Metrics, Fonts, AppStyles} from '../../theme';
import util from '../../util';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background.primary,
  },
  coverImage: {
    backgroundColor: Colors.background.primary,
    height: Metrics.screenHeight - (Metrics.screenHeight * 70) / 100,
  },
  imageStyle: {
    borderRadius: 30,
  },
  bottomViewCont: {
    flex: 1,
    alignSelf: 'center',
    justifyContent: 'flex-end',
    marginBottom: 30,
    alignItems: 'center',
  },
  detailsText: {
    fontSize: Fonts.size.xLarge,
    fontFamily: Fonts.type.bold,
    color: Colors.text.white,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 2,
    alignSelf: 'center',
  },
  subDetailsText: {
    fontFamily: Fonts.type.semiBold,
    fontSize: Fonts.size.small,
    marginTop: 3,
    fontStyle: 'italic',
  },
  dropsSection: {
    ...AppStyles.mTop20,
    ...AppStyles.mBottom20,
    flexDirection: 'row',
    marginHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fireIcon: {
    height: 14,
    width: 14,
    resizeMode: 'contain',
  },
  eventIcon: {
    height: 16,
    width: 16,
    resizeMode: 'contain',
  },
  newDropsText: {
    fontFamily: Fonts.type.semiBold,
    fontSize: Fonts.size.small,
    color: Colors.text.quaternary,
    ...AppStyles.mLeft5,
    bottom: util.isPlatformAndroid() ? 2 : 1,
  },
  dropsListCont: {
    flex: 1,
    marginHorizontal: 15,
    ...AppStyles.mBottom10,
  },
  noCollectionFoundText: {
    fontFamily: Fonts.type.Asap,
    fontSize: Fonts.size.normal,
    color: Colors.text.primary,
    alignSelf: 'center',
    ...AppStyles.mTop20,
  },
  itemEventView: {
    height: 120,
    width: '100%',
    marginVertical: 5,
    borderRadius: 10,
    alignItems: 'center',
  },
  itemEventImage: {
    height: 120,
    width: '100%',
    marginVertical: 5,
    borderRadius: 10,
  },
  eventViewDetail: {
    shadowColor: 'rgba(22,36,49,0.4)',
    shadowOffset: {width: 0, height: -130},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
    height: 120,
    width: '100%',
    marginVertical: 5,
    borderRadius: 10,
  },
  itemEventDateTxt: {
    alignSelf: 'flex-end',
    color: Colors.white,
    fontFamily: Fonts.type.Asap,
    fontSize: Fonts.size.xxSmall,
    marginTop: 5,
    marginRight: 10,
    fontWeight: '600',
  },
  itemEventnNameView: {flexDirection: 'row', flex: 1},
  itemEventNameTxt: {
    alignSelf: 'flex-end',
    color: Colors.white,
    fontFamily: Fonts.type.bold,
    fontSize: Fonts.size.xLarge,
    marginBottom: 5,
    marginHorizontal: 20,
    alignItems: 'flex-end',
  },
  itemEventDispcriptionTxt: {
    color: Colors.white,
    fontFamily: Fonts.type.bold,
    fontSize: Fonts.size.xxSmall,
    marginBottom: 15,
    marginHorizontal: 20,
    alignItems: 'flex-end',
    fontWeight: '400',
  },
  moreButtonImage: {
    height: 8,
    width: 8,
    tintColor: Colors.text.white,
    marginLeft: 8,
    marginTop: 2,
  },
});
