require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'ffmpeg-kit-react-native', :subspecs => ['full-gpl'], :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'

config = use_native_modules!
platform :ios, '12.1'

target 'AHA_MobileApp' do
  # pod 'ffmpeg-kit-react-native/full-gpl', :path => '../node_modules/ffmpeg-kit-react-native'
  # pod 'ffmpeg-kit-react-native/full-gpl', :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'
  # pod 'ffmpeg-kit-react-native', :subspecs => ['full-gpl'], :podspec => '../node_modules/ffmpeg-kit-react-native'
  # pod 'ffmpeg-kit-react-native', :subspecs => ['full-gpl'], :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'

  

  pod 'TwitterKit5'
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
    )
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNConvertPhAsset', :path => '../node_modules/react-native-convert-ph-asset'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
  pod 'GoogleMaps'
 
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary" 
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'react-native-twitter-signin', :path => '../node_modules/react-native-twitter-signin'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  target 'AHA_MobileAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  

post_install do |installer|

# react_project = Xcodeproj::Project.open("../node_modules/react-native/React/React.xcodeproj")
#     react_project.main_group["React/Views"].files.each do |file|   
#       if file.path.match(/^RCTWebView/) 
#         file.remove_from_project
#       end   
#     end   
# react_project.save

  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('12.1') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
      end
    end
  end
end
end
