import {fork} from 'redux-saga/effects';
import user from './user';
import init from './init';
import artists from './artists';
import community from './community';
import interests from './interests';
import vibes from './vibes';
import contentPage from './contentPage';
import dashboard from './dashboard';
import collection from './collection';
import post from './post';
import cart from './cart';
import orderHistory from './orderHistory';
import creditCard from './creditCard';
import wallet from './wallet';
import pin from './pin';
import comments from './comments';
import sales from './sales';
import search from './search';
import notifications from './notifications';
import events from './events';
export default function* root() {
  yield fork(user);
  yield fork(init);
  yield fork(artists);
  yield fork(community);
  yield fork(interests);
  yield fork(vibes);
  yield fork(contentPage);
  yield fork(dashboard);
  yield fork(collection);
  yield fork(post);
  yield fork(cart);
  yield fork(orderHistory);
  yield fork(creditCard);
  yield fork(wallet);
  yield fork(pin);
  yield fork(comments);
  yield fork(sales);
  yield fork(search);
  yield fork(notifications);
  yield fork(events);
}
